[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM *"
    Cross-Origin-Resource-Policy = "cross-origin"
    Content-Security-Policy = "frame-ancestors *;"
    Cross-Origin-Embedder-Policy = "require-corp"
